### ISSUE TITLE
FSEventStreamStart: -21

### ISSUE THREAD

**Issue by fsvehla** [megri/macos-watcher#2]
```
2017-11-01 11:52 java[9999] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)
2017-11-01 11:52 java[9999] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)
2017-11-01 11:52 java[9999] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)
2017-11-01 11:52 java[9999] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)
2017-11-01 11:52 java[9999] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)
2017-11-01 11:52 java[9999] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)
2017-11-01 11:52 java[9999] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)
2017-11-01 11:52 java[9999] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)
[info] Using native WatchService
```

macOS 10.13.1

**Comment by cquiroz** [comment]
I'm seeing the same and then it triggers an OOME

```
2017-11-01 13:45 java[27047] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)
2017-11-01 13:45 java[27047] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)
java.lang.OutOfMemoryError: unable to create new native thread
	at java.lang.Thread.start0(Native Method)
	at java.lang.Thread.start(Thread.java:717)
```

macOS 10.12.6

**Comment by megri** [comment]
I've seen this in some cases as well. I'm not sure if it's the underlying native implementation or SBT that is at fault. There have been similar issues reported on node.js and ember as well.

I'll try to find a solution!

**Comment by megri** [comment]
Can you provide a build that reproduces the issue?

**Comment by fsvehla** [comment]
Earliest possible date is next Tue, but I’ll try then.


On Wed, Nov 1, 2017, at 19:18, megri wrote:
> Can you provide a build that reproduces the issue?


> — You are receiving this because you authored the thread. Reply to
> this email directly, view it on GitHub[1], or mute the thread[2].> 


Links:

  1. https://github.com/megri/macos-watcher/issues/2#issuecomment-341194001

**Comment by aeons** [comment]
Upgrading sbt from 1.0.2 to 1.0.3 fixed this for me.

**Comment by fsvehla** [comment]
Still present for me with 1.0.3

**Comment by aeons** [comment]
Yeah, I got it again after letting it run for some time as well.

**Comment by fgoepel** [comment]
I think it might depend on the MacOS version as well. It's been working for me on an older installation 10.9.5 and consistently fails on 10.13.1 beta with the same project.

**Comment by cquiroz** [comment]
It seems ok on 1.0.3 for me

**Comment by fgoepel** [comment]
After upgrading to MacOS 10.13.2 Beta it starting working for me, so I suspect it's really a problem on the native side.
